# Generated by Django 5.2.6 on 2025-09-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=6, max_digits=18)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('calc_version', models.CharField(default='v1', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['-ts'], name='btc_temp_bi_ts_432e35_idx')],
            },
        ),
    ]
