# Generated by Django 5.2.6 on 2025-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc_temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MvrvZScoreDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(decimal_places=6, max_digits=30, null=True)),
                ('realized_cap', models.DecimalField(decimal_places=6, max_digits=30, null=True)),
                ('zscore', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['-date'], name='btc_temp_mv_date_89bfed_idx')],
            },
        ),
    ]
