# Generated by Django 5.2.6 on 2025-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc_temp', '0002_mvrvzscoredaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRatesDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['-date'], name='btc_temp_fu_date_e01171_idx')],
            },
        ),
        migrations.CreateModel(
            name='RhodlRatioDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['-date'], name='btc_temp_rh_date_723aba_idx')],
            },
        ),
    ]
