# Generated by Django 4.2.25 on 2025-10-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc_temp', '0003_fundingratesdaily_rhodlratiodaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShillerPeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='FundingRatesDaily',
        ),
        migrations.AlterModelOptions(
            name='bitcointemperature',
            options={'ordering': ['-ts']},
        ),
        migrations.AlterField(
            model_name='mvrvzscoredaily',
            name='zscore',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='shillerpedaily',
            index=models.Index(fields=['-date'], name='btc_temp_sh_date_3eed49_idx'),
        ),
    ]
